# Generated by Django 4.0.6 on 2022-08-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.FloatField(default=0),
        ),
    ]
