# Generated by Django 4.0.6 on 2022-08-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_course_credit'),
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docs',
            new_name='Doc',
        ),
    ]
