# Generated by Django 4.0.6 on 2022-08-01 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_rename_docs_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
